### ISSUE TITLE
Repo Size > 700MB [ Optimise ]

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/Trading-Bot#20]
Can we reduce our repo size give me your logical reason i will assign this task Level 2 Task

**Comment by gratusrichard** [comment]
Hello there, I have experience in dealing with machine learning models and by looking at the code, most of the memory is being occupied by the models itself and I believe it would be much more efficient if we stored them inside GIT-LFS instead of git, that way people could clone the repo and then fetch data from LFS .

Kindly assign this to me under gssoc.

**Comment by gratusrichard** [comment]
@Ayushpanditmoto  I have opened a pull request, kindly check it out.
